<Project>
  <PropertyGroup><BaseOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Memory\bin\</BaseOutputPath><BaseIntermediateOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Memory\obj\</BaseIntermediateOutputPath></PropertyGroup>
	<PropertyGroup>
		<MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
	</PropertyGroup>

	<!-- 默认不将引用程序集复制到本地 -->
	<ItemDefinitionGroup>
		<Reference>
			<Private>False</Private>
		</Reference>
	</ItemDefinitionGroup>
</Project>
